### ISSUE TITLE
Finalize Teamwork Contract

### ISSUE THREAD

**Issue by vigneshRajakumar** [UBC-MDS/dsci-522-group14#1]

**Comment by vigneshRajakumar** [comment]
Can we finalize on whether we want to push this doc to the repo? I feel like we can track changes to the doc if we add it to the repo and use the pull-request-review workflow to suggest changes.

Thoughts?

**Comment by camharris22** [comment]
I'm fine pushing the doc to the repo and updating it here. Personally I don't think our Team Contract contained much on the "personal" side.

**Comment by vigneshRajakumar** [comment]
Final decision is to keep this private and to submit to Canvas
