### ISSUE TITLE
Defining problem

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/dsci-522-group14#26]
The problem/question is very clear, which is great. However, there may be some concerns about the objectiveness of good and bad wines. What the is rating based on? Also a small description of the features would be helpful. Nevertheless, your reasoning for the data split was good.

**Comment by vigneshRajakumar** [comment]
We addressed this by adding a caveat in our problem statement: we are using the median score of wine-experts as a proxy for wine quality. Therefore, this model will have that built in: It would predict what the experts would score a wine with a given set of properties. Moreover, we added this is as a note in the final report as well.
