### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/dsci-522-group14#27]
Great download script and use of docopt. Great use of pandas funnctions and your EDA shows a story. How will your correlation heatmap help with model building? Would it be useful to do some comparisons of means to look at important features?

**Comment by vigneshRajakumar** [comment]
Our initial idea was to look at feature correlations to see if we can get any insights for feature selection. We haven't yet done any feature selection/engineering on our model yet and will keep this issue open for the next milestone

**Comment by vigneshRajakumar** [comment]
#53 opened to handle this
