### ISSUE TITLE
Script 4: Analysis script

### ISSUE THREAD

**Issue by vigneshRajakumar** [UBC-MDS/dsci-522-group14#30]
A fourth script that reads the data from the second script, performs some statistical or machine learning analysis and summarizes the results as a figure(s) and a table(s). These should be written to files. This should take two arguments:
- a path/filename pointing to the data
- a path/filename prefix where to write the figure(s)/table(s) to and what to call it (e.g., results/this_analysis)

**Comment by yuyanguo** [comment]
Please use the command below to reproduce the results from script 4(src/ml_model.py)

python src/ml_model.py  --path_1=data/processed/train_set.csv --path_2=data/processed/test_set.csv --out_dir=results/

**Comment by vigneshRajakumar** [comment]
Had a minor change in the docopt needed to be done, handled in #41
