### ISSUE TITLE
Script 5: Report

### ISSUE THREAD

**Issue by vigneshRajakumar** [UBC-MDS/dsci-522-group14#31]
A fifth script: an .Rmd or .ipynb files that presents the key useful (not all!) exploratory data analysis as well as the statistical summaries and figures in a little report. There should be a written narrative in this document that introduces and justifies your question, introduces the data set, presents the findings/results, and interprets the findings/results in context of the question. Some critique of the analysis is also expected (limitations, assumptions, etc) and a statement of future directions (what would you do next if you had more time to work on this). The report is expected to be 1-2 written pages (excluding figures, tables and references). You are expected to have a reference section and cite 2-3 external sources (data source can be one of these citations) in addition to citing the programming languages and packages used.

**Comment by camharris22** [comment]
So, at the moment the final report is in the format of a .Rmd and just needs to be rendered with an R script similar to Tiff's (though at the moment I'm not sure if the output format can be specified the way I have it setup in RStudio). 

I'll test that it at least renders and add this script to the "Usage" part of README. Also, the report currently lives in the 'src' folder but may need to be moved to the 'docs' folder

render final report
Rscript -e "rmarkdown::render('doc/breast_cancer_predict_report.Rmd', output_format = 'github_document')"
