### ISSUE TITLE
Comand line for Download_data.py

### ISSUE THREAD

**Issue by yuyanguo** [UBC-MDS/dsci-522-group14#9]
Please see below the command for downloading the data for the project using the download_data.py script:

python src/download_data.py --url_1=https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv --url_2=https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv --out_file_1=data/winequality-red.csv --out_file_2=data/winequality-white.csv

**Comment by vigneshRajakumar** [comment]
Tested this.
